add_newline = false
command_timeout = 2000

format = '''
$character$directory$git_branch$git_status'''

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
vimcmd_symbol = '[V](bold green)'

[directory]
truncation_length = 1
format = '[$path](bold cyan) '

[git_branch]
# symbol = ""
format = '[[git:\(](bold blue)$branch](bold red)[\)](bold blue)'

[git_status]
format = '([$all_status$ahead_behind](bold red)) '
